name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches: [ "master" ]
    paths:
      - 'monero-blocks/web/**'
      - '!**/*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: monero-blocks/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: monero-watch-web
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
